### ISSUE TITLE
Issues with jmeter plugin for Sonarqube

### ISSUE THREAD

**Issue by ghost** [SonarCommunity/sonar-jmeter#2]
Not sure if this is the correct place to report an issue. I have upgraded to the latest Sonarqube 5.6 LTS and i was using jmeter 0.3 version. Now the plugin no longer supports the latest version?

Exception in thread "main" java.lang.NoSuchMethodError: org.sonar.api.resources.Project.getProperty(Ljava/lang/String;)Ljava/lang/Object;
    at org.sonar.plugins.jmeter.JMeterSensor.analyse(JMeterSensor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
    at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
    at org.sonar.batch.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:83)
    at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:192)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:241)
    at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:236)
    at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:226)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.task.ScanTask.execute(ScanTask.java:47)
    at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
    at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
    at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
    at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:106)
    at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
    at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
    at com.sun.proxy.$Proxy0.execute(Unknown Source)
    at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:240)
    at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
    at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
    at org.sonarsource.scanner.cli.Main.execute(Main.java:72)
    at org.sonarsource.scanner.cli.Main.main(Main.java:60)

**Comment by cfillol** [comment]
Try 0.5-SNAPSHOT: https://github.com/SonarQubeCommunity/sonar-jmeter/releases/download/0.5-RC.1/sonar-jmeter-plugin-0.5-SNAPSHOT.jar

**Comment by ghost** [comment]
Thanks for quick response. The new plugin is working fine with any issues, But then the Images are broken..Attaching the image from the dashboard
![sonar-jmeter-0 5-plugin](https://cloud.githubusercontent.com/assets/4673892/17074203/d0970758-502d-11e6-850f-79e9b573e334.png)

**Comment by akhettar-zz** [comment]
Hi 

I had the same issue and I upgraded to 0.5-snapshot version. I managed to publish JMeter reports to SonarQube but I can't view the JMeter widget on dashboard despite that it has been configured. I can't see anything in the log sonar.log either. I am using the latest Sonarqube 6.1 by the way.
I run sonar-scanner command to publish JTL (in xml format)

 files. I have attached copies of the log and some screenshots for you to view. Any direction would be really appreciated.

Kind regards,

Ayache
<img width="1294" alt="dashboardview" src="https://cloud.githubusercontent.com/assets/996178/19999895/c2714b20-a26c-11e6-8a92-a365e636c96c.png">
<img width="1668" alt="widgetconfigview" src="https://cloud.githubusercontent.com/assets/996178/19999897/c4881ff6-a26c-11e6-8bbb-9b445ea31907.png">

[sonar-scanner.txt](https://github.com/SonarQubeCommunity/sonar-jmeter/files/570999/sonar-scanner.txt)

[JMeterReport.txt](https://github.com/SonarQubeCommunity/sonar-jmeter/files/571010/JMeterReport.txt)

**Comment by ghost** [comment]
We are still facing same issue could not resolve it.  Any help will be appreciated.

**Comment by akhettar-zz** [comment]
@varun7447 so you're able view the JMeter widget on the dashboard, I am not. What version of SonarQube are you using?
Thanks

**Comment by ghost** [comment]
I am unable to view the widget. Images are all broken.
